-- Fifty-Fifty Blame Results Table
CREATE TABLE IF NOT EXISTS fifty_fifty_blame_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user1 TEXT NOT NULL,
  user2 TEXT NOT NULL,
  loser TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Number Guess Blame Results Table
CREATE TABLE IF NOT EXISTS number_guess_blame_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user1 TEXT NOT NULL,
  user2 TEXT NOT NULL,
  number1 INTEGER NOT NULL CHECK (number1 >= 0 AND number1 <= 100),
  number2 INTEGER NOT NULL CHECK (number2 >= 0 AND number2 <= 100),
  target_number INTEGER NOT NULL CHECK (target_number >= 0 AND target_number <= 100),
  loser TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- AI Blame Results Table
CREATE TABLE IF NOT EXISTS ai_analysis_blame_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user1 TEXT NOT NULL,
  user2 TEXT NOT NULL,
  story1 TEXT NOT NULL,
  story2 TEXT NOT NULL,
  loser TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE TABLE snap_roast_blame_results (
    id SERIAL PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    image_url TEXT NOT NULL,
    roast_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_fifty_fifty_created_at ON fifty_fifty_blame_results(created_at);
CREATE INDEX IF NOT EXISTS idx_number_guess_created_at ON number_guess_blame_results(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_analysis_created_at ON ai_analysis_blame_results(created_at);
CREATE INDEX IF NOT EXISTS snap_roast_created_at_idx ON snap_roast_blame_results(created_at); 


-- Comments for documentation
COMMENT ON TABLE fifty_fifty_blame_results IS 'Stores results from the fifty-fifty blame game';
COMMENT ON TABLE number_guess_blame_results IS 'Stores results from the number guessing blame game';
COMMENT ON TABLE ai_analysis_blame_results IS 'Stores results from the AI analysis blame game';

-- Drop script (commented out for safety)
/*
DROP TABLE IF EXISTS fifty_fifty_blame_results;
DROP TABLE IF EXISTS number_guess_blame_results;
DROP TABLE IF EXISTS ai_analysis_blame_results;
*/ 